name: terraform apply

inputs:
  working-directory:
    required: true

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform -chdir=${{ inputs.working-directory }} init
      shell: bash

    - name: Terraform Apply
      run: terraform -chdir=${{ inputs.working-directory }} apply -auto-approve
      shell: bash
