name: Status Badge Action

inputs:
  color1:
    required: true
  badge_name:
    required: true
  github_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Badge Content Setup
      id: setup_badge
      run: |
        color=""        
        if [[ ${{ inputs.color1 }} == 'Diamond' ]]; then
          color="ccca6f"
          echo "DEF"

        elif [[ ${{ inputs.color1 }} == 'Gold' ]]; then
          color="ccac00"

        elif [[ ${{ inputs.color1  }} == 'Silver' ]]; then
          echo "ABC"
          color="bec9c4"
          echo $color

        else
          echo "Expected input value for status badge action: Diamond, Gold, Silver"
          color=""
          exit 1
        fi

        echo ::set-output name=color::$(echo $color)  
        echo ::set-output name=sha::$(git rev-parse --short=5 --verify HEAD)  

        echo $color
      shell: bash

    - name: Setup Badge
      uses: RubbaBoy/BYOB@v1.2.1
      with:
        NAME: ${{ inputs.badge_name }}
        LABEL: ${{ steps.setup_badge.outputs.sha }}
        STATUS: ${{ inputs.color }}
        COLOR: ${{ steps.setup_badge.outputs.color }}
        GITHUB_TOKEN: ${{ inputs.github_token  }}