name: Status Badge Action

inputs:
  color:
    required: true
  badge_name:
    required: true
  github_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Badge Content Setup
      id: setup_badge
      run: |
        badge_color=""        
        if [[ ${{ inputs.color }} == 'Diamond' ]]; then
          badge_color="00007f"

        elif [[ ${{ inputs.color }} == 'Gold' ]]; then
          badge_color="ccac00"

        elif [[ ${{ inputs.color  }} == 'Paper' ]]; then
          #badge_color="999999"
          badge_color="9FC5E8"

        else
          echo "Expected input value for status badge action: Diamond, Gold, Silver"
          exit 1
        fi

        echo ::set-output name=badge_color::$(echo $badge_color)  
        echo ::set-output name=sha::$(git rev-parse --short=5 --verify HEAD)  

        echo $badge_color
      shell: bash

    - name: Setup Badge
      uses: RubbaBoy/BYOB@v1.2.1
      with:
        NAME: ${{ inputs.badge_name }}
        LABEL: ${{ steps.setup_badge.outputs.sha }}
        LABEL:
        STATUS: ${{ inputs.color }}
        COLOR: ${{ steps.setup_badge.outputs.badge_color }}
        GITHUB_TOKEN: ${{ inputs.github_token  }}