= Detailed Security Configuration - Updated

== Overview

This section is meant to provide an opinionated approach towards the
implementation security controls by domain. Although the approaches may
not be a fit for all use cases or complete for production use, they are
meant to guide the reader towards current best practices and design
considerations to achieve security control objectives.

=== *Controls and Architectures*

The information provided in the table below is compiled from product
documentation, blog posts, white papers and other resources and
emphasize recommended configurations that ensure Red Hat OpenShift
Security and Platform Integrity.


|===
|*Security Domain*|*Control & Architectural Suggestions*|*References*
|*Authentication & Authorization*
|
|




|*Security Monitoring & Alerting*
|
|
|*Does the service you are evaluating offer Auditing Capabilities*
a| In OpenShift Container Platform, auditing occurs at both a host operating system context and at an OpenShift API context.

Auditing of the host operating system consists of the standard auditing capabilities provided by the auditd service in Red Hat Enterprise Linux
(RHEL) and Red Hat CoreOS (RHCOS). Audit is enabled by default in Red Hat Enterprise Linux CoreOS (RHCOS); however, the audit subsystem is running in a default configuration and without any audit rules. The auditd configuration ( /etc/audit/auditd.conf ) file should be modified as necessary to meet common organizational audit requirements such as retention and fault tolerance. Additionally, audit rules must be configured to record events.

Auditing at the OpenShift context consists of recording the HTTP requests made to the OpenShift API. The OpenShift API consists of two
components : the Kubernetes API server and the OpenShift API server. Both of these components provide an audit log, each recording the events that
have affected the system by individual users, administrators, or other components of the system. OpenShift API audit is enabled by default and is produced by both the kube-apiserver and openshift-apiserver components. The audit configuration of each is defined by a combination of default settings and corresponding custom resources named KubeAPIServer and OpenShiftAPIServer, respectively. For more information, consult the Kubernetes Auditing documentation https://kubernetes.io/docs/tasks/debug-application-cluster/audit/.

1 - Edit the APIServer resource:
----
$ oc edit apiserver cluster
----

2 - Update the spec.audit.profile field:

----
apiVersion: config.openshift.io/v1
  kind: APIServer
  metadata:
  ...
  spec:
    audit:
      profile: WriteRequestBodies
----

3 - Save the file to apply the changes.

4 - Verify that a new revision of the Kubernetes API server pods has rolled out. This will take several minutes.
----
$ oc get kubeapiserver -o=jsonpath='{range .items[0].status.conditions[?(@.type=="NodeInstallerProgressing")]}{.reason}{"\n"}{.message}{"\n"}'
----


a|
* Configuring the audit log policy: https://docs.openshift.com/container-platform/4.7/security/audit-log-policy-config.html

* Viewing audit logs: https://docs.openshift.com/container-platform/4.7/security/audit-log-view.html#audit-log-view

* Auditing the OS: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/auditing-the-system_security-hardening


| *Enable FIPS Compliance*
| You can install an OpenShift Container Platform cluster that uses FIPS Validated / Modules in Process cryptographic libraries on the x86_64 architecture.

For the Red Hat Enterprise Linux CoreOS (RHCOS) machines in your cluster, this change is applied when the machines are deployed based on the status of an option in the install-config.yaml file, which governs the cluster options that a user can change during cluster deployment. With Red Hat Enterprise Linux (RHEL) machines, you must enable FIPS mode when you install the operating system on the machines that you plan to use as worker machines. These configuration methods ensure that your cluster meet the requirements of a FIPS compliance audit: only FIPS Validated / Modules in Process cryptography packages are enabled before the initial system boot.

*Because FIPS must be enabled before the operating system that your cluster uses boots for the first time, you cannot enable FIPS after you deploy a cluster.*

To install a cluster in FIPS mode, follow the instructions to install a customized cluster on your preferred infrastructure. Ensure that you set fips: true in the install-config.yaml file before you deploy your cluster.


a|

* Enabling FIPS Compliance: https://docs.openshift.com/container-platform/4.7/installing/installing-fips.html

|*Encryption* Encrypting ETCD after install
a| By default, etcd data is not encrypted in OpenShift Container Platform. You can enable etcd encryption for your cluster to provide an additional layer of data security. For example, it can help protect the loss of sensitive data if an etcd backup is exposed to the incorrect parties.

When you enable etcd encryption, the following OpenShift API server and Kubernetes API server resources are encrypted:

Secrets

Config maps

Routes

OAuth access tokens

OAuth authorize tokens

When you enable etcd encryption, encryption keys are created. These keys are rotated on a weekly basis. *You must have these keys in order to restore from an etcd backup.*

1 - Modify the APIServer object:

----
$ oc edit apiserver
----

2 - Set the encryption field type to aescbc:
----
spec:
  encryption:
    type: aescbc
----

3 - Save the file to apply the changes. The encryption process starts. It can take 20 minutes or longer for this process to complete, depending on the size of your cluster.

4 - Verify that etcd encryption was successful.
----
$ oc get openshiftapiserver -o=jsonpath='{range .items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}'
----
The output shows EncryptionCompleted upon successful encryption:
----
EncryptionCompleted
All resources encrypted: secrets, configmaps
----




a|
* Encrypting ETCD: https://docs.openshift.com/container-platform/4.7/security/encrypting-etcd.html

|*How does the service you are evaluating handle Encryption in Transit?*
a| With IPsec enabled, all network traffic between nodes on the OVN-Kubernetes Container Network Interface (CNI) cluster network travels through an encrypted tunnel.

*Types of network traffic flows encrypted by IPsec*

With IPsec enabled, only the following network traffic flows between pods are encrypted:

Traffic between pods on different nodes on the cluster network

Traffic from a pod on the host network to a pod on the cluster network

The following traffic flows are not encrypted:

Traffic between pods on the same node on the cluster network

Traffic between pods on the host network

Traffic from a pod on the cluster network to a pod on the host network

The encrypted and unencrypted flows are illustrated in this https://docs.openshift.com/container-platform/4.7/networking/ovn_kubernetes_network_provider/about-ipsec-ovn.html[diagram]

Enable IPsec for the OVN-Kubernetes network provider https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#modifying-nwoperator-config-startup_installing-bare-metal-network-customizations[details]:

*Prerequisites:*

Create the install-config.yaml file and complete any modifications to it.

Create the Ignition config files for your cluster.

*Procedure:*

1 - Change to the directory that contains the installation program and create the manifests:
----
$ ./openshift-install create manifests --dir=<installation_directory>
----

2 - Create a stub manifest file for the advanced network configuration that is named cluster-network-03-config.yml in the <installation_directory>/manifests/ directory:
----
$ cat <<EOF > <installation_directory>/manifests/cluster-network-03-config.yml
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
EOF
----
3 - Open the cluster-network-03-config.yml file in an editor and specify the advanced network configuration for your cluster, such as in the following examples:

__Enable IPsec for the OVN-Kubernetes network provider__
----
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  defaultNetwork:
    ovnKubernetesConfig:
      ipsecConfig: {}
----


a|
* IPsec encryption configuration: https://docs.openshift.com/container-platform/4.7/networking/ovn_kubernetes_network_provider/about-ipsec-ovn.html


|===
